server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ap_project_db
spring.datasource.username=AP-Project
spring.datasource.password=A12345678$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect