CREATE SEQUENCE IF NOT EXISTS advertisement_images_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS advertisements_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS cities_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS conversations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS favorites_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS seller_ratings_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE advertisement_images
(
    advertisement_id BIGINT,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url        VARCHAR(255),
    CONSTRAINT advertisement_images_pkey PRIMARY KEY (id)
);

CREATE TABLE advertisements
(
    category_id BIGINT,
    city_id     BIGINT,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    BIGINT                                  NOT NULL,
    price       BIGINT,
    description VARCHAR(255),
    status      VARCHAR(255),
    title       VARCHAR(255),
    CONSTRAINT advertisements_pkey PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_category_id BIGINT,
    name               VARCHAR(255),
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE TABLE cities
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    province VARCHAR(255),
    CONSTRAINT cities_pkey PRIMARY KEY (id)
);

CREATE TABLE conversations
(
    advertisement_id BIGINT,
    buyer_id         BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_id        BIGINT,
    CONSTRAINT conversations_pkey PRIMARY KEY (id)
);

CREATE TABLE favorites
(
    advertisement_id BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT,
    CONSTRAINT favorites_pkey PRIMARY KEY (id)
);

CREATE TABLE messages
(
    conversation_id BIGINT,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id       BIGINT,
    sent_at         TIMESTAMP WITHOUT TIME ZONE,
    text            VARCHAR(255),
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE seller_ratings
(
    score            INTEGER                                 NOT NULL,
    advertisement_id BIGINT,
    buyer_id         BIGINT,
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seller_id        BIGINT,
    comment          VARCHAR(255),
    CONSTRAINT seller_ratings_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    average_rating DOUBLE PRECISION                        NOT NULL,
    rating_count   INTEGER                                 NOT NULL,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email          VARCHAR(255),
    full_name      VARCHAR(255),
    password       VARCHAR(255),
    phone_number   VARCHAR(255),
    role           VARCHAR(255),
    status         VARCHAR(255),
    username       VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE conversations
    ADD CONSTRAINT fk11fycx5lvegp8mwplgsl8401h FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE seller_ratings
    ADD CONSTRAINT fk30hol51cet8e889a2kshfhewp FOREIGN KEY (advertisement_id) REFERENCES advertisements (id) ON DELETE NO ACTION;

ALTER TABLE messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE seller_ratings
    ADD CONSTRAINT fk6roc4ao7836p72mjgp91e2ks2 FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE favorites
    ADD CONSTRAINT fk72uxvox97iy1p0eec5gr1f2n0 FOREIGN KEY (advertisement_id) REFERENCES advertisements (id) ON DELETE NO ACTION;

ALTER TABLE advertisements
    ADD CONSTRAINT fk7bv11qwlmp1gci1mwsll3mrqd FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE categories
    ADD CONSTRAINT fk9il7y6fehxwunjeepq0n7g5rd FOREIGN KEY (parent_category_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE conversations
    ADD CONSTRAINT fkdfc04e2rwgsjaji2rlcbwjjes FOREIGN KEY (advertisement_id) REFERENCES advertisements (id) ON DELETE NO ACTION;

ALTER TABLE seller_ratings
    ADD CONSTRAINT fkdu4ucenaaye96s56amainomcn FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE advertisements
    ADD CONSTRAINT fkdukgo76w2yes5uh7uv8iyqrrs FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE NO ACTION;

ALTER TABLE conversations
    ADD CONSTRAINT fkgcmb2bq98wunnce1y9pyj9sp6 FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE favorites
    ADD CONSTRAINT fkk7du8b8ewipawnnpg76d55fus FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE advertisement_images
    ADD CONSTRAINT fkmhfv2s52mmildcptpsyrrq0jw FOREIGN KEY (advertisement_id) REFERENCES advertisements (id) ON DELETE NO ACTION;

ALTER TABLE advertisements
    ADD CONSTRAINT fkq2bx00e2ngwnvvuneonbnemvj FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE messages
    ADD CONSTRAINT fkt492th6wsovh1nush5yl5jj8e FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE NO ACTION;